import 'dart:collection';

import 'apply_result.dart';
import 'constants.dart';
import 'gamesave.dart';
import 'player_record.dart';
import 'roster_key.dart';
import 'schedule.dart';

enum _Mode { sequential, lookupAndModify, schedule, teamData, coachData, freeAgent }

/// Groups incoming player lines by position and returns them in [kPositionNames]
/// order via [toList].  Within each position group insertion order is preserved
/// (= depth-chart order supplied by the input file).
class _PlayerBucket {
  final Map<String, List<String>> _buckets = {};

  void add(String position, String line) {
    (_buckets[position] ??= []).add(line);
  }

  List<String> toList() {
    final result = <String>[];
    for (final pos in kPosOrder) {
      result.addAll(_buckets[pos] ?? []);
    }
    // Any position not in kPosOrder goes at the end, order preserved.
    for (final entry in _buckets.entries) {
      if (!kPosOrder.contains(entry.key)) result.addAll(entry.value);
    }
    return result;
  }
}

/// Parses delimited player-data text and applies it to a [NFL2K4Gamesave].
///
/// **Sequential mode** (default): `Team = xxx` sections are processed in order;
/// players within each section are assigned to the team's pointer-array slots in
/// the same order they appear in the file.  This is correct for round-trips of
/// files generated by [NFL2K4Gamesave.toText].
///
/// **LookupAndModify mode**: activated by a `LookupAndModify` line in the file.
/// Each data line is matched to a player by first + last name (with optional
/// position and PBP disambiguation).  Teams may appear in any order and players
/// may appear in any order.  A `Team = xxx` line resets the mode back to
/// Sequential.
///
/// **Key resolution** (highest priority first):
///   1. `Key=field1,field2,...` directive encountered during parsing — also persists to [RosterKey.current]
///      (`Key=` alone resets [RosterKey.current] to [RosterKey.all])
///   2. [key] parameter passed to [applyText]
///   3. [RosterKey.current] (session state; defaults to [RosterKey.all])
///
/// **`?` / `_` sentinels**: any column whose value is `?` or `_` is skipped
/// without modifying the player record.
class InputParser {
  final NFL2K4Gamesave _save;

  static final _deleteCommas = RegExp(r',\s*$');
  static final _teamRegex = RegExp(r'^Team\s*=', caseSensitive: false);
  static final _autoDepthChartRe = RegExp(r'^\s*autoupdatedepthchart\s*$', caseSensitive: false, multiLine: true);
  static final _compressFARe = RegExp(r'^\s*compressfa=(\d+)\s*$', caseSensitive: false, multiLine: true);


  InputParser(this._save);

  ApplyResult applyText(String text, {RosterKey? key}) {
    final errors = <String>[];
    int updated = 0, skipped = 0;

    // Detect delimiter: semicolons beat commas when more frequent.
    final semiCount = ';'.allMatches(text).length;
    final commaCount = ','.allMatches(text).length;
    final delim = semiCount > commaCount ? ';' : ',';

    RosterKey activeKey = key ?? RosterKey.current;

    final autoUpdateDepthChart = _autoDepthChartRe.hasMatch(text);

    final compressFAMatch = _compressFARe.firstMatch(text);
    if (compressFAMatch != null) {
      _applyCompressFA(int.parse(compressFAMatch.group(1)!), errors);
    }

    _Mode mode = _Mode.sequential;
    List<PlayerRecord> currentTeamPlayers = [];
    int teamCursor = 0;
    Map<String, Queue<PlayerRecord>> faBuckets = {};
    // activeBucket collects incoming lines grouped by position (only when
    // autoUpdateDepthChart is true).  sectionPlayersBuf holds the physical
    // PlayerRecords in slot order.  On flush, bucket.toList()[i] is written
    // to sectionPlayersBuf[i] so slot 0 always gets the first sorted line.
    _PlayerBucket? activeBucket = autoUpdateDepthChart ? _PlayerBucket() : null;
    final sectionPlayersBuf = <PlayerRecord>[];

    void flushSectionBuf() {
      if (activeBucket == null || sectionPlayersBuf.isEmpty) return;
      final sortedLines = activeBucket!.toList();
      for (int i = 0; i < sortedLines.length && i < sectionPlayersBuf.length; i++) {
        final cols = _splitLine(sortedLines[i], delim);
        final player = sectionPlayersBuf[i];
        bool anySet = false;
        for (int j = 0; j < activeKey.fields.length && j < cols.length; j++) {
          final value = cols[j].trim();
          if (value == '?' || value == '_' || value.isEmpty) continue;
          try {
            player.setAttribute(activeKey.fields[j], value);
            anySet = true;
          } catch (e) {
            errors.add('${player.fullName}: failed to set ${activeKey.fields[j]}="$value": $e;');
          }
        }
        if (anySet) updated++;
      }
      activeBucket = _PlayerBucket();
      sectionPlayersBuf.clear();
    }
    final scheduleLines = <String>[];   // accumulates schedule content
    List<String>? teamDataFields;       // active team data key fields
    List<String>? coachDataFields;      // active coach data key fields
    bool autoFixSkin = false;           // set by AutoFixSkinFromPhoto directive
    bool vrabelFix = false;

    for (final rawLine in text.split(RegExp(r'[\r\n]+'))) {
      // Strip trailing comma and whitespace.
      final line = rawLine.trim().replaceAll(_deleteCommas, '');
      if (line.isEmpty || line.startsWith('#')) continue;

      // ── PlayerControlled= directive ─────────────────────────────────────
      if (line.toLowerCase().startsWith('playercontrolled=')) {
        final rhs = line.substring('playercontrolled='.length).trim();
        if (!_save.isFranchise) {
          errors.add('PlayerControlled= ignored: file is not a franchise save.');
          continue;
        }
        if (rhs.toLowerCase() == 'all') {
          for (int t = 0; t < 32; t++) { _save.setTeamPlayerControlled(t, true); }
        } else {
          // Parse [Team1,Team2,...] or Team1,Team2,...
          final inner = rhs.startsWith('[') && rhs.endsWith(']')
              ? rhs.substring(1, rhs.length - 1)
              : rhs;
          final names = inner.split(',').map((s) => s.trim()).where((s) => s.isNotEmpty).toList();
          // Set all to false first, then enable the listed teams.
          for (int t = 0; t < 32; t++) { _save.setTeamPlayerControlled(t, false); }
          for (final name in names) {
            final idx = _resolveTeamIndex(name);
            if (idx < 0) {
              errors.add('PlayerControlled: unknown team "$name"');
            } else {
              _save.setTeamPlayerControlled(idx, true);
            }
          }
        }
        continue;
      }

      // ── AutoFixSkinFromPhoto directive ────────────────────────────────────
      if (line.trim().toLowerCase() == 'autofixskinfromphoto') {
        autoFixSkin = true;
        continue;
      }

      if (line.trim().toLowerCase() == 'autoupdatedepthchart') {
        // Already took care of this one with text search at the beginning
        continue;
      }

      //vrabelFix
      if (line.trim().toLowerCase() == 'vrabelfix') {
        vrabelFix = true;
        continue;
      }

      if (line.trim().toLowerCase() == 'autoupdatepbp') {
        _save.autoUpdatePBP();
        continue;
      }

      if (line.trim().toLowerCase() == 'autoupdatephoto') {
        _save.autoUpdatePhoto();
        continue;
      }


      // ── CompressFA= directive ────────────────────────────────────────────
      if (line.toLowerCase().startsWith('compressfa=')) continue; // handled above

      // ── TeamDataKey= directive ───────────────────────────────────────────
      if (line.toLowerCase().startsWith('teamdatakey=')) {
        teamDataFields = line.substring('teamdatakey='.length)
            .split(delim)
            .map((f) => f.trim())
            .where((f) => f.isNotEmpty)
            .toList();
        mode = _Mode.teamData;
        continue;
      }

      // ── CoachKey= directive ─────────────────────────────────────────────
      if (line.toLowerCase().startsWith('coachkey=')) {
        coachDataFields = line.substring('coachkey='.length)
            .split(delim)
            .map((f) => f.trim())
            .where((f) => f.isNotEmpty)
            .toList();
        mode = _Mode.coachData;
        continue;
      }

      // ── Key= directive ───────────────────────────────────────────────────
      if (line.toLowerCase().startsWith('key=')) {
        flushSectionBuf();
        final rhs = line.substring(4).trim();
        if (rhs.isEmpty) {
          activeKey = RosterKey.current = RosterKey.all;
        } else {
          try {
            activeKey = RosterKey.current = RosterKey.parse(rhs);
          } catch (e) {
            errors.add('Invalid Key directive: $e');
          }
        }
        continue;
      }

      // ── YEAR= / Week header → schedule mode ──────────────────────────────
      if ( line.toLowerCase().startsWith('week') || line.toLowerCase().startsWith('year') ) {
        mode = _Mode.schedule;
      }

      // ── Schedule mode: accumulate game lines ──────────────────────────────
      if (mode == _Mode.schedule) {
        scheduleLines.add(line);
        continue;
      }

      // ── Mode switches ────────────────────────────────────────────────────
      if (line.toLowerCase().contains('lookupandmodify')) {
        mode = _Mode.lookupAndModify;
        continue;
      }

      // ── Team = xxx ───────────────────────────────────────────────────────
      if (_teamRegex.hasMatch(line)) {
        flushSectionBuf();
        mode = _Mode.sequential; // Team= always resets to sequential
        final eqIdx = line.indexOf('=');
        String teamName = line.substring(eqIdx + 1);
        if (teamName.contains('Players:')) {
          teamName = teamName.substring(0, teamName.indexOf('Players:'));
        }
        teamName = teamName.trim();

        final teamNameLower = teamName.toLowerCase();
        if (teamNameLower == 'freeagents' || teamNameLower == 'fa') {
          mode = _Mode.freeAgent;
          faBuckets = {};
          for (final p in _save.getFreeAgentPlayers()) {
            (faBuckets[p.position] ??= Queue()).add(p);
          }
        } else {
          final idx = _resolveTeamIndex(teamName);
          if (idx >= 0) {
            currentTeamPlayers = _save.getTeamPlayers(idx);
          } else {
            errors.add('Unknown team: "$teamName"');
            currentTeamPlayers = [];
          }
        }
        teamCursor = 0;
        continue;
      }

      // ── Team data line ───────────────────────────────────────────────────
      if (mode == _Mode.teamData) {
        final fields = teamDataFields;
        if (fields == null) continue;
        final cols = _splitLine(line, delim);
        if (cols.isEmpty) continue;
        final ti = fields.indexWhere((f) => f.toLowerCase() == 'team');
        if (ti < 0 || ti >= cols.length) {
          errors.add('TeamData line missing "team" column: $line');
          skipped++;
          continue;
        }
        final teamName = cols[ti].trim();
        final teamIdx = _resolveTeamIndex(teamName);
        if (teamIdx < 0 || teamIdx >= 32) {
          errors.add('Unknown or non-NFL team: "$teamName"');
          skipped++;
          continue;
        }
        bool anySet = false;
        for (int i = 0; i < fields.length && i < cols.length; i++) {
          final fieldName = fields[i];
          if (fieldName.toLowerCase() == 'team') continue;
          final value = cols[i].trim();
          if (value == '?' || value == '_' || value.isEmpty) continue;
          try {
            _save.setTeamField(teamIdx, fieldName, value);
            anySet = true;
          } catch (e) {
            errors.add('Team "$teamName": failed to set $fieldName="$value": $e');
          }
        }
        if (anySet) updated++;
        continue;
      }

      // ── Coach data line ─────────────────────────────────────────────────
      if (mode == _Mode.coachData) {
        final fields = coachDataFields;
        if (fields == null) continue;
        final cols = _splitLine(line, delim);
        if (cols.isEmpty) continue;
        final ti = fields.indexWhere((f) => f.toLowerCase() == 'team');
        if (ti < 0 || ti >= cols.length) {
          errors.add('Coach line missing "team" column: $line');
          skipped++;
          continue;
        }
        final teamName = cols[ti].trim();
        final teamIdx = _resolveTeamIndex(teamName);
        if (teamIdx < 0 || teamIdx >= 32) {
          errors.add('Unknown or non-NFL team for coach: "$teamName"');
          skipped++;
          continue;
        }
        bool anySet = false;
        for (int i = 0; i < fields.length && i < cols.length; i++) {
          final fieldName = fields[i];
          if (fieldName.toLowerCase() == 'team') continue;
          final value = cols[i].trim();
          if (value == '?' || value == '_' || value.isEmpty) continue;
          try {
            _save.setCoachAttribute(teamIdx, fieldName, value);
            anySet = true;
          } catch (e) {
            errors.add('Coach "$teamName": failed to set $fieldName="$value": $e');
          }
        }
        if (anySet) updated++;
        continue;
      }

      // ── Data line ────────────────────────────────────────────────────────
      final cols = _splitLine(line, delim);
      if (cols.isEmpty) continue;

      PlayerRecord? player;

      if (mode == _Mode.freeAgent) {
        final pi = _fieldIndex(activeKey, 'position');
        if (pi < 0 || pi >= cols.length) {
          errors.add('FreeAgents section requires position in key: $line');
          skipped++;
          continue;
        }
        final pos = cols[pi].trim();
        final bucket = faBuckets[pos];
        if (bucket == null || bucket.isEmpty) {
          final fi = _fieldIndex(activeKey, 'fname');
          final li = _fieldIndex(activeKey, 'lname');
          final fname = (fi >= 0 && fi < cols.length) ? cols[fi].trim() : '?';
          final lname = (li >= 0 && li < cols.length) ? cols[li].trim() : '?';
          errors.add('FreeAgents: no slot for $pos $fname $lname (skipped)');
          skipped++;
          continue;
        }
        player = bucket.removeFirst();
      } else if (mode == _Mode.sequential) {
        if (teamCursor < currentTeamPlayers.length) {
          if (activeBucket != null) {
            final pi = _fieldIndex(activeKey, 'position');
            final pos = pi >= 0 && pi < cols.length ? cols[pi].trim() : '';
            activeBucket!.add(pos, line);
            sectionPlayersBuf.add(currentTeamPlayers[teamCursor++]);
          } else {
            player = currentTeamPlayers[teamCursor++];
          }
        } else {
          errors.add('Team player limit reached; skipping: $line');
          skipped++;
        }
        if (activeBucket != null) continue;
      } else {
        // LookupAndModify: find player by name.
        final fi = _fieldIndex(activeKey, 'fname');
        final li = _fieldIndex(activeKey, 'lname');
        if (fi < 0 || li < 0 || fi >= cols.length || li >= cols.length) {
          errors.add('LookupAndModify requires fname and lname in key: $line');
          skipped++;
          continue;
        }
        final fname = cols[fi].trim();
        final lname = cols[li].trim();
        final pi = _fieldIndex(activeKey, 'position');
        final pos = (pi >= 0 && pi < cols.length) ? cols[pi].trim() : null;
        final bi = _fieldIndex(activeKey, 'pbp');
        final pbpStr = (bi >= 0 && bi < cols.length) ? cols[bi].trim() : null;

        player = _findPlayer(fname, lname, pos, pbpStr, errors);
        if (player == null) {
          skipped++;
          continue;
        }
      }

      // Apply attributes.
      bool anySet = false;
      for (int i = 0; i < activeKey.fields.length && i < cols.length; i++) {
        final fieldName = activeKey.fields[i];
        final value = cols[i].trim();
        if (value == '?' || value == '_' || value.isEmpty) continue;
        try {
          player!.setAttribute(fieldName, value);
          anySet = true;
        } catch (e) {
          if(player != null){
            errors.add('${player!.fullName}: failed to set $fieldName="$value": $e;');
          } else {
            errors.add("Error with line: '$line'");
          }
        }
      }
      if (anySet) updated++;
    }

    flushSectionBuf();

    // ── Apply accumulated schedule data ──────────────────────────────────────
    if (scheduleLines.isNotEmpty) {
      if (!_save.isFranchise) {
        errors.add('Schedule data ignored: file is not a franchise save.');
      } else {
        final existing = _save.getSchedule();
        final result = parseScheduleText(scheduleLines.join('\n'), existing);
        errors.addAll(result.errors);
        _save.setSchedule(result.weeks);
      }
    }

    // ── AutoFixSkinFromPhoto post-processing ─────────────────────────────────
    if (autoFixSkin) {
      _save.autoFixSkinFromPhoto();
    }

    // ── AutoUpdateDepthChart post-processing ─────────────────────────────────
    if (autoUpdateDepthChart ) {
      _save.fixKrPrWithCbs();
    }

    if(vrabelFix){
      _save.vrabelFix();
    }

    return ApplyResult(updated: updated, skipped: skipped, errors: errors);
  }

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  void _applyCompressFA(int count, List<String> errors) {
    final fas = _save.getFreeAgentPlayers();
    final start = (fas.length - count).clamp(0, fas.length);
    for (int i = start; i < fas.length; i++) {
      try {
        fas[i].setAttribute('fname', 'f');
        fas[i].setAttribute('lname', 'a');
      } catch (e) {
        errors.add('CompressFA: failed to shrink FA slot $i: $e');
      }
    }
  }

  static int _fieldIndex(RosterKey key, String name) =>
      key.fields.indexWhere((f) => f.toLowerCase() == name.toLowerCase());

  int _resolveTeamIndex(String name) {
    final q = name.toLowerCase();
    // Exact match first.
    for (int i = 0; i < kTeamNames.length; i++) {
      if (kTeamNames[i].toLowerCase() == q) return i;
    }
    // Partial match fallback.
    for (int i = 0; i < kTeamNames.length; i++) {
      if (kTeamNames[i].toLowerCase().contains(q)) return i;
    }
    return -1;
  }

  PlayerRecord? _findPlayer(
      String fname, String lname, String? pos, String? pbpStr,
      List<String> errors) {
    final all = _save
        .findPlayers('$fname $lname')
        .where((m) =>
            m.player.firstName == fname && m.player.lastName == lname)
        .toList();

    if (all.isEmpty) {
      errors.add('Player not found: $fname $lname');
      return null;
    }
    if (all.length == 1) return all.first.player;

    // If all matches share the same PBP they are the same physical record
    // referenced from multiple team slots — treat as unambiguous.
    final pbpValues = all.map((m) => m.player.pbp).toSet();
    if (pbpValues.length == 1) return all.first.player;

    // Disambiguate by position.
    if (pos != null) {
      final byPos = all.where((m) => m.player.position == pos).toList();
      if (byPos.length == 1) return byPos.first.player;
      // Position narrows to a same-PBP group → same physical record.
      final byPosPbp = byPos.map((m) => m.player.pbp).toSet();
      if (byPosPbp.length == 1) return byPos.first.player;
    }

    // Disambiguate by PBP.
    if (pbpStr != null) {
      final pbp = int.tryParse(pbpStr);
      if (pbp != null) {
        final byPbp = all.where((m) => m.player.pbp == pbp).toList();
        if (byPbp.isNotEmpty) {
          final byPbpSet = byPbp.map((m) => m.player.pbp).toSet();
          if (byPbp.length == 1 || byPbpSet.length == 1) return byPbp.first.player;
        }
      }
    }

    errors.add('Ambiguous player: $fname $lname (${all.length} matches)');
    return null;
  }

  /// Splits a line on [delim], handling RFC-4180 quoting for comma-mode.
  static List<String> _splitLine(String line, String delim) {
    if (delim != ',') return line.split(delim);

    final fields = <String>[];
    final cur = StringBuffer();
    bool inQuotes = false;
    for (int i = 0; i < line.length; i++) {
      final c = line[i];
      if (inQuotes) {
        if (c == '"' && i + 1 < line.length && line[i + 1] == '"') {
          cur.write('"');
          i++;
        } else if (c == '"') {
          inQuotes = false;
        } else {
          cur.write(c);
        }
      } else if (c == ',' ) {
        fields.add(cur.toString());
        cur.clear();
      } else if (c == '"' && cur.isEmpty) {
        // Only enter quote mode at the START of a field.
        // This lets unquoted values like 6'5" pass through as literals.
        inQuotes = true;
      } else {
        cur.write(c);
      }
    }
    fields.add(cur.toString());
    return fields;
  }
}
